/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.app;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;

import accessone.app.AccessOneConfiguration;
import accesstwo.app.AccessTwoConfiguration;
import manager.app.ManagerConfiguration;
import engine.EngineConfiguration;
import serviceproxy.ServiceProxyConfiguration;
import serviceproxy.helpers.ServiceLoader;
import serviceproxy.proxy.ServiceProxy;
import serviceproxy.pubsub.EventPublisher;
import serviceproxy.secret.SecretStore;
import serviceproxy.proxy.ProxyType;

@SpringBootApplication
@Import({ 
    ServiceProxyConfiguration.class, 
    ManagerConfiguration.class, 
    EngineConfiguration.class,
    AccessOneConfiguration.class,
    AccessTwoConfiguration.class
})
public class Application {

    public static void main(String[] args) {
        var app = new SpringApplication(Application.class);
        // app.setWebApplicationType(WebApplicationType.NONE);
        app.run(args);
    }

    @Bean
    public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
        return args -> {
            ServiceLoader.registerServices(ctx, ProxyType.InProc);
            ServiceProxy.init(ProxyType.InProc);
            EventPublisher.init(ProxyType.InProc);
            SecretStore.init(ProxyType.InProc);
            // ServiceLoader.registerServices(List.of(HelloServer.class, HelloOne.class, HelloTwo.class));
            // var caller = ctx.getBean(ServiceCaller.class);
            // caller.call();
            // caller.publish();
            // caller.getSecrets();

        };
    }
}
