/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.app;

import java.util.List;
import com.google.inject.Guice;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.core.config.Configurator;

import accessone.app.AccessOneModule;
import accessone.interfaces.HelloOne;
import accesstwo.app.AccessTwoModule;
import accesstwo.interfaces.HelloTwo;
import client.app.ServiceCaller;
import serviceproxy.helpers.ServiceLoader;
import serviceproxy.proxy.ServiceProxy;
import serviceproxy.server.ExposedService;
import serviceproxy.proxy.ProxyType;
import serviceproxy.proxy.ProxyModule;
import server.app.DaprModule;
import server.interfaces.HelloServer;
import org.reflections.Reflections;
import org.reflections.scanners.TypeAnnotationsScanner;
public class App {
    public static void main(String[] args) throws Exception {
        Configurator.setRootLevel(Level.DEBUG);

        var injector = Guice.createInjector(new ProxyModule(), new DaprModule(), new AccessOneModule(),
                new AccessTwoModule());

        ServiceProxy.init(ProxyType.InProc, injector);

        ServiceLoader.init(injector);
        ServiceLoader.registerServices(List.of(HelloServer.class, HelloOne.class, HelloTwo.class));

        var caller = new ServiceCaller();
        caller.call();
        caller.publish();
        caller.getSecrets();
    }
}
