/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.app;

import com.google.inject.Guice;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.core.config.Configurator;

import accessone.app.AccessOneModule;
import accesstwo.app.AccessTwoModule;
import client.app.ServiceCaller;
import serviceproxy.helpers.ServiceLoader;
import serviceproxy.proxy.ServiceProxy;
import serviceproxy.proxy.ProxyType;
import serviceproxy.proxy.ProxyModule;
import server.app.DaprModule;

public class App {
    public static void main(String[] args) throws Exception {
        Configurator.setRootLevel(Level.DEBUG);

        var injector = Guice.createInjector(new ProxyModule(), new DaprModule(), new AccessOneModule(),
                new AccessTwoModule());

        ServiceProxy.init(ProxyType.InProc, injector);

        ServiceLoader.init(injector);

        var caller = new ServiceCaller();
        caller.call();
        caller.publish();
        caller.getSecrets();
    }
}
