/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.app;

import java.util.LinkedList;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;

import accessone.app.AccessOneConfiguration;
import accessone.app.interfaces.HelloOne;
import accesstwo.app.AccessTwoConfiguration;
import accesstwo.app.interfaces.HelloTwo;
import client.app.ClientConfiguration;
import client.app.ServiceCaller;
import server.ServerConfiguration;
import server.interfaces.HelloServer;
import serviceproxy.ServiceProxyConfiguration;
import serviceproxy.helpers.ServiceLoader;
import serviceproxy.proxy.ServiceProxy;
import serviceproxy.server.ExposedService;
import serviceproxy.proxy.ProxyType;

@SpringBootApplication
@Import({ ServiceProxyConfiguration.class, ClientConfiguration.class, ServerConfiguration.class,
        AccessOneConfiguration.class, AccessTwoConfiguration.class, })
public class Application {

    public static void main(String[] args) {
        var app = new SpringApplication(Application.class);
        app.setWebApplicationType(WebApplicationType.NONE);
        app.run(args);
    }

    @Bean
    public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
        return args -> {
            // System.out.println("Let's inspect the beans provided by Spring Boot:");

            // String[] beanNames = ctx.getBeanDefinitionNames();
            // Arrays.sort(beanNames);
            // for (String beanName : beanNames) {
            // System.out.println(beanName);
            // }

            ServiceLoader.registerServices(ctx);
            ServiceProxy.init(ProxyType.InProc);
            // ServiceLoader.registerServices(List.of(HelloServer.class, HelloOne.class, HelloTwo.class));
            var caller = ctx.getBean(ServiceCaller.class);
            caller.call();
            caller.publish();
            caller.getSecrets();

        };
    }

    // public static void main(String[] args) throws Exception {
    // Configurator.setRootLevel(Level.DEBUG);

    // var injector = Guice.createInjector(new ProxyModule(), new DaprModule(), new
    // AccessOneModule(),
    // new AccessTwoModule());

    // ServiceProxy.init(ProxyType.InProc, injector);

    // ServiceLoader.init(injector);

    // var caller = new ServiceCaller();
    // caller.call();
    // caller.publish();
    // caller.getSecrets();
    // }
}
