/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.app;

import com.google.inject.Guice;

import client.app.ServiceCaller;
import common.proxy.ProxySettings;
import common.proxy.ServiceProxy;
import server.app.DaprModule;

public class App {
    public static void main(String[] args) throws Exception {

        var injector = Guice.createInjector(new DaprModule());
        
        var settings = new ProxySettings();
        settings.type = "dapr";
        settings.pubsubName = "pubsub";
        settings.secretStoreName = "secretstore";
        settings.injector = injector;
        ServiceProxy.init(settings);

        // final var service = injector.getInstance(DaprServer.class);
        // service.start(5000);
        // service.RegisterSubscribers("pubsub", List.of(HelloService.class));
        // service.awaitTermination();
        var caller = new ServiceCaller();
        caller.call();
    }
}
