/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.app;

import java.util.List;

import com.budbee.proto.HelloRequest;
import com.google.inject.Guice;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.core.config.Configurator;

import client.app.ServiceCaller;
import common.helpers.ServiceLoader;
import common.proxy.ClassServiceProxy;
import common.proxy.ProxySettings;
import common.proxy.ProxyType;
import common.proxy.ServiceProxy;
import server.app.DaprModule;
import server.interfaces.Hello;

public class App {
    public static void main(String[] args) throws Exception {
        Configurator.setRootLevel(Level.DEBUG);

        var injector = Guice.createInjector(new DaprModule());

        var settings = new ProxySettings();
        settings.type = ProxyType.InProc;
        settings.pubsubName = "pubsub";
        settings.secretStoreName = "secrets.json";
        ServiceProxy.init(settings);

        ServiceLoader.init(injector);
        ServiceLoader.registerServices(List.of(Hello.class));
        ServiceLoader.registerSubscribers("pubsub");

        var proxy = ClassServiceProxy.create(Hello.class);
        var res = proxy.hello(HelloRequest.newBuilder().setText("New proxy!").setOtherText("Other").build());
        System.out.println("Res " + res.result.getText());

        var caller = new ServiceCaller();
        caller.call();
        caller.publish();
        caller.getSecrets();
    }
}
